using Microsoft.Extensions.Options;

namespace CRM.Api.Customers.Attachments;

public sealed class LocalFileStorage : IFileStorage
{
    private readonly string _root;

    public LocalFileStorage(IOptions<AttachmentsOptions> options, IWebHostEnvironment env)
    {
        var configuredRoot = options.Value.StorageRoot;
        _root = Path.IsPathRooted(configuredRoot)
            ? configuredRoot
            : Path.Combine(env.ContentRootPath, configuredRoot);
        _root = Path.GetFullPath(_root);
    }

    public async Task SaveAsync(Stream content, string storageKey, CancellationToken ct)
    {
        var path = ResolvePath(storageKey);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        try
        {
            await using var fileStream = new FileStream(
                path, FileMode.Create, FileAccess.Write, FileShare.None, bufferSize: 4096, useAsync: true);
            await content.CopyToAsync(fileStream, ct);
        }
        catch (Exception ex) when (ex is UnauthorizedAccessException or IOException)
        {
            throw new StorageException("Failed to save the attachment to storage.", ex);
        }
    }

    public Task<Stream> OpenReadAsync(string storageKey, CancellationToken ct)
    {
        var path = ResolvePath(storageKey);
        try
        {
            Stream stream = File.OpenRead(path);
            return Task.FromResult(stream);
        }
        catch (Exception ex) when (ex is UnauthorizedAccessException or IOException)
        {
            throw new StorageException("Failed to read the attachment from storage.", ex);
        }
    }

    public Task DeleteAsync(string storageKey, CancellationToken ct)
    {
        var path = ResolvePath(storageKey);
        try
        {
            File.Delete(path);
        }
        catch (FileNotFoundException)
        {
            // Idempotent: already gone.
        }
        catch (DirectoryNotFoundException)
        {
            // Idempotent: already gone.
        }
        return Task.CompletedTask;
    }

    // storageKey is always generated by CustomerAttachmentEndpoints (never client-supplied),
    // but this containment check stays as a defense-in-depth guard against path traversal.
    private string ResolvePath(string storageKey)
    {
        var fullPath = Path.GetFullPath(Path.Combine(_root, storageKey));
        if (!fullPath.StartsWith(_root, StringComparison.Ordinal))
        {
            throw new UnauthorizedAccessException("Resolved storage path escapes the storage root.");
        }
        return fullPath;
    }
}

public sealed class StorageException : Exception
{
    public StorageException(string message, Exception inner) : base(message, inner)
    {
    }
}
